import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "./globals.css";

import { Metadata } from "next";
import { Header } from "@/components";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Jasmine Dragon",
    template: "%s - Jasmine Dragon",
  },
  description: "Generated by Next.js",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
